export const Data = [
  {
    language: 'spanish',
    header: {
      home: 'inicio',
      about: 'sobre mí',
      projects: 'proyectos',
      contact: 'contacto',
    },
    intro: {
      greeting: 'hola mundo!',
      text1: 'soy',
      text2: 'Josu',
      text3: 'Hernandez',
      description: 'desarrollador web frontend',
      button: 'Ver CV',
    },
    about: {
      p1: 'Soy un apasionado de los viajes y de la tecnología al que desde pequeño le gusta enrredar en coches, motos y ordenadores.',
      p2: 'No fue hasta hace un año que descubrí mi pasión por el desarrollo web del cual estoy constantemente haciendo cursos y aprendiendo porque siempre pongo todo mi compromiso en lo que hago.',
      text1: 'quién',
      text2: 'soy',
    },
    work: {
      text1: 'mis',
      text2: 'proyectos',
      button1: 'ver código',
      button2: 'ver web',
    },
    contact: {
      text1: 'métodos de ',
      text2: 'contacto',
    },
    resume: {
      certificates: 'Certificados y Estudios',
      knowledge: 'Conocimientos',
      languages: 'Idiomas',
      japanese: 'Japonés',
      english: 'Inglés',
      spanish: 'Español',
      button: 'Inicio',
      high: 'Avanzado',
      native: 'Nativo',
      p1: 'Soy un entusiasta del desarrollo web frontend con el objetivo de crear páginas web fáciles de usar, full responsive y animadas. Para ello cuento con un amplio conocimiento en HTML, CSS, Javascript y React.',
      p2: 'Soy una persona que disfruta aprendiendo todos los dias, trabajando en equipo y muy comprometido con lo que hago.',
    },
  },
  {
    language: 'english',
    header: {
      home: 'home',
      about: 'about',
      projects: 'work',
      contact: 'contact',
    },
    intro: {
      greeting: 'hello world!',
      text1: "I'm",
      text2: 'Josu',
      text3: 'Hernandez',
      description: 'frontend web developer',
      button: 'resume',
    },
    about: {
      p1: 'Traveling is one of my passions and since I was a kid the other one has been manipulating cars, motorbikes and computers.',
      p2: "Around one year ago I figured out I love developing webs. I love the idea of create something from scratch and that is why I've been working hard, taking courses and learning about frontend to offer to you an excellent service.",
      text1: 'who',
      text2: 'am i',
    },
    work: {
      text1: 'my',
      text2: 'projects',
      button1: 'view code',
      button2: 'view web',
    },
    contact: {
      text1: 'contact ',
      text2: 'methods',
    },
    resume: {
      certificates: 'Certificates',
      knowledge: 'Skills',
      languages: 'Languages',
      japanese: 'Japanese',
      english: 'English',
      spanish: 'Spanish',
      button: 'Home',
      high: 'High',
      native: 'Native',
      p1: 'I am loving web development and my goal is to create easy to use websites as well as animated full responsive websites. I have extensive knowledge in HTML, CSS, Javascript y React that I use for it.',
      p2: 'I am a person who enjoys learning every day, working as a team and very committed to what I do.',
    },
  },
  {
    language: 'japanese',
    header: {
      home: 'ホーム',
      about: '自己紹介',
      projects: '経験',
      contact: '問合せ先',
    },
    intro: {
      greeting: 'おはよう！',
      text1: 'エルナンデス',
      text2: 'ジョス',
      text3: 'です',
      description: 'フロントエンドwebプログラマー',
      button: '履歴書',
    },
    about: {
      p1: '旅行が大好きだし、車やバイクやコンピューターが大好きな人です。',
      p2: '一年前webプログラミングが大好きなことになって、私は毎日一所懸命プログラミングの勉強を始まりました。',
      text1: '誰',
      text2: 'ですか',
    },
    work: {
      text1: '私の',
      text2: 'プロジェクト',
      button1: 'コードを見る',
      button2: 'webを見る',
    },
    contact: {
      text1: '連絡',
      text2: '方法',
    },
    resume: {
      certificates: '知識',
      knowledge: 'スキル',
      languages: '言語',
      japanese: '日本語',
      english: '英語',
      spanish: 'スペイン語',
      button: 'ホーム',
      high: '強い',
      native: '自国語',
      p1: '私はwebプログラミングが大好きで簡単で使えるし、アニメーションがあるwebを作れるために、頑張ってHTMLもCSSもJavascriptもReactも学びました。',
      p2: 'その上、いつも一所懸命働いて、グループで働く事が好きです。',
    },
  },
]
